### ISSUE TITLE
Highlights with triple quotes

### ISSUE THREAD

**Issue by Quar** [gwenzek/scalaSublimeSyntax#2] opened 2017-06-07 20:27 UTC
First of all, thanks for making this great ScalaSyntax package!

In an extreme case with four consecutive quotes (detect string literals using regex):
```Scala
""""[^"]"""".r
```
which was supposed to be interpreted equivalent to `"\"[^\"]\"*"`.

![single quote inside triple quotes](https://preview.ibb.co/i3dnyF/Screen_Shot_2017_06_07_at_1_58_17_PM.png)

Not sure yet if this was actually a bug in sublime syntax though.

**Comment by gwenzek** [comment] 2017-06-07 21:08
Hi, thanks for the report.
I haven't look into it,
But did you try with the official Scala syntax?

I did this syntax a while ago, and meanwhile the official version have
seriously improved, and have similar features.

The official version also have more conventional scope names and probably
has been tested more.

I still prefer my version though (I didn't manage to push all of my
personal preferences, into the main one).

**Comment by Quar** [comment] 2017-06-07 21:27
Thanks for the reminding! I have just checked the official Scala syntax, although without warning highlights on quadruple quotes, it is hard for me to read whether its agree or disagree with the syntax.

Honestly I am quite confused with the official syntax, for example, it still lacks consistency on highlighting `=>`, where `=` was highlighted and `>` is not. I still prefer your version.

**Comment by Quar** [comment] 2017-06-07 23:11
Perhaps this can be fixed by:
 - [Scala2.sublime-syntax: Line 525](https://github.com/gwenzek/scalaSublimeSyntax/blob/master/Scala2.sublime-syntax#L526) 
replace this line with
``` yaml
    - match: \\u[0-9a-fA-F]{4}
      scope: constant.character.escape.scala
``` 
 - [Scala2.sublime-syntax: Line 526](https://github.com/gwenzek/scalaSublimeSyntax/blob/master/Scala2.sublime-syntax#L526) 
change match pattern `'"""'` to be backward-greedy `'("*)"""'`

Reasons:
 - Triple quoted strings in Scala are multiline literals, within which unicode escapes work, but escape sequence will not [[SLS-1.3.5]](https://www.scala-lang.org/files/archive/spec/2.12/01-lexical-syntax.html#string-literals).  Therefore it might be helpful not highlight escaped sequence.
 - Multiline literals starts with triple quotes, no matter what afterwards, but stops with the last three consecutive quotes out of no-less-than-three (>=3) consecutive quotes. For example:
     * `"""a""""` is equivalent to `"a\""`
     * `"""a"""""""` is equivalent to `"a\"\"\"\""`
     * `"""a""""""" length` is equivalent to `("a\"\"\"\"").length`, though without dot a postfix warning will be thrown

**Comment by gwenzek** [comment] 2017-07-27 14:09
Thanks for looking into it.
You were right the triple quotes string weren't handling properly the
closing and escaped characters.

I added a few tests.
I'll update the thread once the changes are live.
I will also release a few fixes and tweaks of scope names by the same
occasion.

**Comment by gwenzek** [comment] 2017-08-06 12:55
I just published the new version.
Package Control should pick it up in a few hours.

Please re-open if the issue is not fixed.

**Closed as completed by gwenzek** 2017-08-06 12:55 UTC
