### ISSUE TITLE
Formating broken after << operator

### ISSUE THREAD

**Issue by ktercjak** [gwenzek/scalaSublimeSyntax#3] opened 2017-08-06 08:23 UTC
inserting
`var x= z<<4`
breaks syntax formating

**Comment by gwenzek** [comment] 2017-08-06 12:57
I just tried your snippet with the latest version and it looks fine.
I've just released it your issue should be fixed when Package Control update this package.

Please re-open if the issue is not fixed.

**Closed as completed by gwenzek** 2017-08-06 12:57 UTC
